const quotes = [
    { "text": "Thành công không phải là cuối cùng, thất bại không phải là chết chóc: đó là lòng can đảm để tiếp tục.", "author": "Winston Churchill" },
    { "text": "Đừng đợi đến khi mọi thứ hoàn hảo mới bắt đầu. Bắt đầu sẽ làm mọi thứ trở nên hoàn hảo.", "author": "Khuyết danh" },
    { "text": "Kỷ luật là cầu nối giữa mục tiêu và thành tựu.", "author": "Jim Rohn" },
    { "text": "Nếu bạn muốn đi nhanh, hãy đi một mình. Nếu bạn muốn đi xa, hãy đi cùng nhau.", "author": "Ngạn ngữ Phi Châu" },
    { "text": "Sự kiên trì chính là khác biệt lớn nhất giữa thành công và thất bại.", "author": "Steve Jobs" },
    { "text": "Đừng so sánh chương 1 của mình với chương 20 của người khác.", "author": "Khuyết danh" },
    { "text": "Hôm nay đầy rẫy những khó khăn, và ngày mai cũng không hề dễ dàng. Nhưng sau ngày mai, mọi thứ sẽ trở nên tốt đẹp.", "author": "Jack Ma" },
    { "text": "Cách tốt nhất để dự đoán tương lai là tự tạo ra nó.", "author": "Abraham Lincoln" },
    { "text": "Bạn không cần phải vĩ đại để bắt đầu, nhưng bạn phải bắt đầu để trở nên vĩ đại.", "author": "Zig Ziglar" },
    { "text": "Giới hạn duy nhất cho những thành tựu ngày mai là những hoài nghi của chúng ta ngày hôm nay.", "author": "Franklin D. Roosevelt" },
    { "text": "Cứ hướng về phía mặt trời, bóng tối sẽ ngả về sau bạn.", "author": "Walt Whitman" },
    { "text": "Đừng bao giờ từ bỏ ước mơ chỉ vì mất quá nhiều thời gian để thực hiện. Thời gian vẫn sẽ trôi đi thôi.", "author": "Earl Nightingale" },
    { "text": "Khó khăn không phải để dừng bước, khó khăn là để rèn luyện bản lĩnh.", "author": "Khuyết danh" },
    { "text": "Mọi giấc mơ đều có thể trở thành hiện thực nếu chúng ta đủ can đảm để theo đuổi chúng.", "author": "Walt Disney" },
    { "text": "Đừng đếm những gì bạn đã mất, hãy quý trọng những gì bạn đang có và lên kế hoạch cho những gì sẽ đạt được.", "author": "Khuyết danh" },
    { "text": "Hành trình vạn dặm bắt đầu từ một bước chân đầu tiên.", "author": "Lão Tử" },
    { "text": "Làm việc khi họ đang ngủ. Học hỏi khi họ đang chơi. Tiết kiệm khi họ đang chi tiêu. Và sống giấc mơ khi họ đang ao ước.", "author": "Khuyết danh" },
    { "text": "Thành công là việc đi từ thất bại này đến thất bại khác mà không mất đi lòng nhiệt huyết.", "author": "Winston Churchill" },
    { "text": "Sự đầu tư vào kiến thức luôn mang lại lãi suất cao nhất.", "author": "Benjamin Franklin" },
    { "text": "Đừng để ý kiến của người khác lấn át tiếng nói bên trong bạn.", "author": "Steve Jobs" },
    { "text": "Không có gì là không thể với một người luôn biết cố gắng.", "author": "Alexander Đại Đế" },
    { "text": "Người chiến thắng không bao giờ bỏ cuộc, và người bỏ cuộc không bao giờ chiến thắng.", "author": "Vince Lombardi" },
    { "text": "Cuộc sống chỉ thực sự bắt đầu khi bạn bước ra khỏi vùng an toàn của mình.", "author": "Neale Donald Walsch" },
    { "text": "Đừng tập trung vào việc vượt qua người khác, hãy tập trung vào việc vượt qua chính mình của ngày hôm qua.", "author": "Khuyết danh" },
    { "text": "Nơi nào có ý chí, nơi đó có con đường.", "author": "Ngạn ngữ Anh" },
    { "text": "Sáng tạo là khi trí thông minh được vui chơi.", "author": "Albert Einstein" },
    { "text": "Thời gian của bạn là có hạn, đừng lãng phí nó để sống cuộc đời của người khác.", "author": "Steve Jobs" },
    { "text": "Chỉ những người dám thất bại lớn mới có thể đạt được thành công lớn.", "author": "Robert F. Kennedy" },
    { "text": "Bạn sẽ không bao giờ cảm thấy hối tiếc vì đã nỗ lực hết mình.", "author": "Khuyết danh" },
    { "text": "Hãy làm những việc khó khăn khi chúng còn dễ dàng và làm những việc lớn lao khi chúng còn nhỏ bé.", "author": "Lão Tử" },
    { "text": "May mắn là sự chuẩn bị gặp gỡ cơ hội.", "author": "Seneca" },
    { "text": "Bạn sinh ra là một bản chính, đừng chết như một bản sao.", "author": "John Mason" },
    { "text": "Hãy sống như thể ngày mai bạn sẽ chết. Hãy học như thể bạn sẽ sống mãi mãi.", "author": "Mahatma Gandhi" },
    { "text": "Mục tiêu mà không có kế hoạch thì chỉ là một điều ước.", "author": "Antoine de Saint-Exupéry" },
    { "text": "Cách duy nhất để làm được những điều vĩ đại là yêu những gì bạn làm.", "author": "Steve Jobs" },
    { "text": "Đừng sợ đi chậm, chỉ sợ đứng yên.", "author": "Ngạn ngữ Trung Quốc" },
    { "text": "Cuộc đời là 10% những gì xảy ra với bạn và 90% cách bạn phản ứng với nó.", "author": "Charles R. Swindoll" },
    { "text": "Kẻ thắng không bao giờ từ bỏ, kẻ từ bỏ không bao giờ thắng.", "author": "Napoléon Hill" },
    { "text": "Sai lầm lớn nhất bạn có thể mắc phải trong đời là luôn sợ hãi mình sẽ mắc sai lầm.", "author": "Elbert Hubbard" },
    { "text": "Để thành công, khao khát thành công của bạn phải lớn hơn nỗi sợ thất bại.", "author": "Bill Cosby" },
    { "text": "Người duy nhất bạn nên cố gắng để giỏi hơn chính là bạn của ngày hôm qua.", "author": "Khuyết danh" },
    { "text": "Thái độ quan trọng hơn trình độ.", "author": "Khuyết danh" },
    { "text": "Hãy tin rằng bạn có thể và bạn đã đi được nửa chặng đường rồi.", "author": "Theodore Roosevelt" },
    { "text": "Bạn không bao giờ quá già để đặt ra một mục tiêu khác hoặc mơ một giấc mơ mới.", "author": "C.S. Lewis" },
    { "text": "Dấu hiệu của sự thông minh không phải là kiến thức mà là trí tưởng tượng.", "author": "Albert Einstein" },
    { "text": "Hãy làm việc trong im lặng và để thành công của bạn lên tiếng.", "author": "Frank Ocean" },
    { "text": "Mỗi ngày là một cơ hội mới để thay đổi cuộc đời bạn.", "author": "Khuyết danh" },
    { "text": "Đừng để ngày hôm qua chiếm quá nhiều thời gian của ngày hôm nay.", "author": "Will Rogers" },
    { "text": "Mọi chuyện đều có vẻ bất khả thi cho đến khi nó được hoàn thành.", "author": "Nelson Mandela" },
    { "text": "Nghị lực và kiên trì sẽ chiến thắng tất cả.", "author": "Benjamin Franklin" }
];

export default quotes;